apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-pvc
  labels:
    app: n8n
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # Adjust storage as needed
